library("shiny")
library("devtools")
install_github("syounkin/ITHIM")
library("ITHIM")
runGitHub( "ITHIM-UI", "syounkin")

library("shiny")
library("devtools")
install("~/ITHIM/")
runApp("~/ITHIM-UI/")
